### ISSUE TITLE
warning: update peer dependencies to support graphql 0.12.x

### ISSUE THREAD

**Issue by eballeste** [apollographql/apollo-tracing#15]
`apollo-tracing@0.1.1 requires a peer of graphql@^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.`

**Comment by deinspanjer** [comment]
Getting this same error, but with 14.1.1 not being accepted.
npm WARN apollo-tracing@0.4.0 requires a peer of graphql@0.10.x - 14.0.x but none is installed. You must install peer dependencies yourself.

**Comment by donaldboulton** [comment]
Same here with 14.1.1

**Comment by fguitton** [comment]
Now still producing the same output with recent graphql@14.2.1
```
yarn install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-bc00ed6f-7f64-49ef-ba70-6cbd5fdc88a8 > borderline-server-gql > apollo-server-express > apollo-server-core > apollo-tracing@0.5.2" has incorrect peer dependency "graphql@0.10.x - 14.1.x".
[4/4] Building fresh packages...
```

**Comment by ca1123** [comment]
Have same problem here when installing @vue/cli 3.6.3

**Comment by abernix** [comment]
The `apollo-tracing` npm package lives in the `apollo-server` repository, and this should be fixed in the latest versions:

https://github.com/apollographql/apollo-server/blob/378f4580d762563913ae08210d2d175496c035a5/packages/apollo-tracing/package.json#L17-L19
