### ISSUE TITLE
Spec question - is the tracing times just for field fetching or for complete field resolution

### ISSUE THREAD

**Issue by bbakerman** [apollographql/apollo-tracing#2]
There are 2 stages to field fetching in graphql - the raw field resolver stage and then the complete field resolution of that field and its sub values.

Given a `user` field query like this

```
     user(id:1234) {
          name
          friends {
              name
         }
    }     
```

I just wanted to confirm the tracing times are for the "fetch" of the user(id:1234) object OR is it the fetch + the resolution times of the sub fields?

I am guessing its just the fetch time.  The spec currently says:

> The duration of a resolver call is relative to the resolver call start.

But its not explicit on that this is.  Can we please make it more explicit.

**Comment by martijnwalraven** [comment]
Sorry, I somehow completely missed this because it turns out I wasn't watching the repo.
