### ISSUE TITLE
[question] Tracing validation errors

### ISSUE THREAD

**Issue by aliok** [apollographql/apollo-tracing#22]
/label question

Is there a way to have apollo-tracing logging validation errors?

See https://github.com/apollographql/apollo-server/blob/master/packages/apollo-tracing/src/index.ts#L54

What's necessary to support that?

**Comment by abernix** [comment]
Sorry for the very delayed response here.  This repository is the home of the tracing specification and not the home of the `apollo-tracing` _npm_ package itself (which as you linked above, is within the `apollo-server` repository on GitHUb).

The `apollo-tracing` library captures timings.  Validation errors can be captured using [Apollo Graph Manager](https://engine.apollographql.com) (e.g. previously Apollo Engine), or with an [Apollo Server plugin](https://www.apollographql.com/docs/apollo-server/integrations/plugins/#end-hooks) which provides a callback (which acts as a _validation did end_ handler) to the `validationDidStart` life-cycle hook.  In fact, there is an example of precisely capturing validation errors in the documentation there!

Hope this helps!
