### ISSUE TITLE
Next.js Support

### ISSUE THREAD

**Issue by b-gibbs** [apollographql/apollo-tracing#28]
In moving from Express to the Next.js API server, I'm losing support for Apollo Studio. Perhaps apollo-server-micro doesn't support tracing? Are there any plans to add support for the engine to report the schema via apollo-server-micro served through the Next.js API routes?

**Comment by sakhmedbayev** [comment]
I think the issue is with CORS. Next.js' API routes by default set to 'same-origins'. I cannot find a way to make it work with apollo-server-micro.

**Comment by abernix** [comment]
This would be an issue and a question for the `apollo-server-micro`, not this repository, which is merely a (technical) specification for the tracing format structure.  (Ultimately, this should just be a matter of setting the right headers.)

There's a minimal example of how to deal with CORS on [the `README` of the `apollo-server-micro` package's npm page](https://npm.im/apollo-server-micro).  (which is published from [the README in the monorepo here](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-micro/README.md#cors-example))
