### ISSUE TITLE
support for apollo-server-lambda

### ISSUE THREAD

**Issue by adikari** [apollographql/apollo-tracing#30]
I am using `apollo-server-lambda`. Tracing is not working for me so wondering if its supported or not?

**Comment by abernix** [comment]
I'm not sure of anything that should prevent it from working, however, this repository is for the tracing technical specification and nothing more.  The `apollo-server-lambda` package lives in the https://github.com/apollographql/apollo-server/.  I'd expect it to work the same as other integrations (e.g., `apollo-server-express`).  In looking for a solution, please put together a more complete minimal reproduction demonstrating how you've attempted to accomplish this (and perhaps try the most popular `apollo-server-express` with a similar configuration to see if you can reproduce it in both cases) and open it on that repository for a better chance at getting assistance.

Thanks!
