### ISSUE TITLE
module init issue in combination with `aws xray sdk`

### ISSUE THREAD

**Issue by Kosta-Github** [apollographql/apollo-tracing#7]
This seems to be a newer issue, since I have used it in combination together for a while now, but suddenly the behaviour changed:

When I am using `graphql-server-express` in combination with `aws-xray-sdk` on `AWS Lambda` I am now getting a module init error for the `apollo-tracing` module and something related to Promise.resolve() & type error while requiring `apollo-tracing`.

If I am disabling the `aws-xray-sdk`, it starts working again.

Is that a known issue?

Since I am more interested in `xray` than `apollo-tracing` right now and `apollo-tracing` still being in an experimental state: is there a way to disable this module within `graphql-server-express` somehow?

I am using:
    "aws-sdk": "^2.121.0",
    "aws-xray-sdk": "^1.1.4",
    "aws-serverless-express": "^3.0.2",
    "express": "^4.15.4",
    "graphql-server-express": "^1.1.2"

**Comment by martijnwalraven** [comment]
Could you post the exact error output you get?

**Comment by Kosta-Github** [comment]
something like this:
```
module initialization error: TypeError
at new WrappedPromise (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1332:120)
at Function.resolve (native)
at Object.9.apollo-tracing (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:706:31)
at s (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:683)
at /var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:734
at Object.7../graphqlOptions (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:438:18)
at s (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:683)
at /var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:734
at Object.11.apollo-server-core (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:823:28)
at s (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:683)
at /var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:734
at Object.12../connectApollo (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:876:23)
at s (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:683)
at /var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:734
at Object.564.apollo-server-express (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:47608:10)
at s (/var/task/_optimize/fluent-package-backend-dev-express/src/express/lambda.js:1:683)
```
with the corresponding lines extracted like this (since I cannot send you the full source package):
```
1332:      var _this = _possibleConstructorReturn(this, (WrappedPromise.__proto__ || Object.getPrototypeOf(WrappedPromise)).call(this, wrappedExecutor));

706: var resolvedPromise = Promise.resolve();

438: var runQuery_1 = require("./runQuery");

823: var apollo_server_core_1 = require("apollo-server-core");

876: var expressApollo_1 = require("./expressApollo");

47608: __export(require("apollo-server-express"));
```
I hope this helps a bit...

**Comment by martijnwalraven** [comment]
Is `WrappedPromise` one of your own classes? Or part of `aws-xray-sdk`?

**Comment by Kosta-Github** [comment]
It is coming implicitly from `xray` defined by the `async-listener`:
```
├─┬ aws-xray-sdk@1.1.4
│ ├─┬ aws-xray-sdk-core@1.1.4
│ │ ├─┬ continuation-local-storage@3.2.0
│ │ │ ├─┬ async-listener@0.6.8
```

**Comment by Kosta-Github** [comment]
looks like this came in just 2 days ago via this commit: https://github.com/othiym23/async-listener/commit/58f2e0ea29464a1f35f61795e6aa9ee7aa3f6fb7

**Comment by Kosta-Github** [comment]
going back to version `async-listener@0.6.7` solves the issue temporarily for me...

I am still not sure, if the root cause of this issue is with this module, `xray`, or `async-listener`...

**Comment by martijnwalraven** [comment]
I'm glad that solved it for you! I have no idea what `xray` or `async-listener` do, but the code and dependencies of `apollo-tracing` are pretty minimal. (This is actually the wrong repository for this, the code for the JavaScript package lives [here](https://github.com/apollographql/apollo-tracing-js).)

**Comment by abernix** [comment]
As noted above, this is the repository for the Apollo Tracing spec.  The actual `apollo-tracing` package lives in [the Apollo Server repository](https://github.com/apollographql/apollo-server/tree/378f4580d762563913ae08210d2d175496c035a5/packages/apollo-tracing/) now.

If you're still having problems here, please open an issue over there!
