### ISSUE TITLE
Add sections for query parsing and validation

### ISSUE THREAD

**Issue by ind1go** [apollographql/apollo-tracing#8]
The spec as I see it offers plenty of support for the individual data fetchers, but sometimes a significant proportion of the query may be taken up by its parsing into an AST and its validation.

Could these areas be added to the specification? I might imagine something similar to this (note the "parse" and "validate" keys):

```json
{
  "data": ...,
  "errors": ...,
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": ...,
      "endTime": ...,
      "duration": ...,
      "execution": {
        "parse": {
          "startOffset": ...,
          "duration": ...,
        },
        "validate": {
          "startOffset": ...,
          "duration": ...,
        },
        "resolvers": [
          {
            "path": [..., ...],
            "parentType": ...,
            "fieldName": ...,
            "returnType": ...,
            "startOffset": ...,
            "duration": ...,
          },
          ...
        ]
      }
    }
  }
}
```

**Comment by martijnwalraven** [comment]
This is definitely something I would like to add. In fact, the reason we put an `execution` key in there was exactly to leave room for other phases. So what I'd imagine would be `parsing` and `validation` at the same level as `execution`.

**Comment by ind1go** [comment]
Ah, you mean you envisaged `execution` being a sibling of `parsing` and `validation`, rather than containing them? Here's an updated example:

```json
{
  "data": ...,
  "errors": ...,
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": ...,
      "endTime": ...,
      "duration": ...,
      "parsing": {
        "startOffset": ...,
        "duration": ...,
      },
      "validation": {
        "startOffset": ...,
        "duration": ...,
      },
      "execution": {
        "resolvers": [
          {
            "path": [..., ...],
            "parentType": ...,
            "fieldName": ...,
            "returnType": ...,
            "startOffset": ...,
            "duration": ...,
          },
          ...
        ]
      }
    }
  }
}
```

By the by... any idea when `apollo-tracing` will be in Optics? I'm running a `graphql-java` server and running without agents would be ideal.

**Comment by martijnwalraven** [comment]
@ind1go: We'll be releasing a public preview soon, but if you hit me up on the Apollo slack (`martijnwalraven`) we could also get you into early access.

**Comment by ind1go** [comment]
Thanks for looking at the PR! What's the state of that suggestion in terms of the spec - i.e. if I made  a pull request on [graphql-java/graphql-java](https://github.com/graphql-java/graphql-java) to add in the parsing and validation instrumentation, is the addition to the spec (a) likely to be sufficiently 'correct' to be implemented elsewhere, and (b) likely to be used in Engine in the near future?

**Comment by martijnwalraven** [comment]
@ind1go: Even though it's not currently implemented anywhere, we always had this in mind when designing the spec. I don't expect any changes, so I think it should be safe to add support to server libraries.

I talked to the Engine team about this as well, and they are definitely excited about taking advantage of the extra information as well. I can't give you an exact timeframe for it because we're still working towards a GA release and other things are higher priority, but 'near future' seems about right :)

**Comment by ind1go** [comment]
Great! https://github.com/graphql-java/graphql-java/pull/784
